### PR TITLE
Move setup to academy/setup.html

### PR DESCRIPTION
**Pull request by c-martinez**
@mkuzak , I quite like how the rest of the index.html is organized, thought the setup could also be organized in the same way. What do you think?

### CODE REVIEW

**Comment by mkuzak** [comment]
I like it, but the more you diverge from original template the harder it will be for you to merge all the improvements and updates coming in.

**Comment by c-martinez** [comment]
Is it a change we should propose upstream then?

**Comment by mkuzak** [comment]
I think so

**Comment by c-martinez** [comment]
Sent [PR upstream](https://github.com/swcarpentry/workshop-template/pull/436).

**Pull request closed without merging**
